_G["LWB"] = _G["LWB"] or {}
local LWB = _G["LWB"]
local L = LibStub("AceLocale-3.0"):NewLocale("LWB","deDE")
if not L then return end


L["1 Charge"] = "1 Aufladung" -- Needs review
L["Absorbed:"] = "Absorbiert:" -- Needs review
L["Added to Blacklist"] = "[PlayerName] wird jetzt blockiert." -- Needs review
L["Add Player"] = "Spieler hinzuf\195\188gen" -- Needs review
L["Add Player Desc"] = "F\195\188gt einen Spieler hinzu, um Nachrichten aus dieser Liste zu empfangen" -- Needs review
L["Alert to Self"] = "Alamiert mich selbst" -- Needs review
L["Alert to Self Desc"] = "Alamiert dich, wenn etwas mit deinem Lichtbrunnen passiert" -- Needs review
L["Already Blacklisted"] = "[PlayerName] wird bereits blockiert." -- Needs review
L["Already in List"] = "Spieler schon in der Liste [aktuelleListe] vorhanden" -- Needs review
L["Battleground"] = "Schlachtfeld" -- Needs review
L["Begin Pulsing"] = "Beginne pulsieren" -- Needs review
L["Blacklist"] = "Blacklist" -- Needs review
L["Blacklist Desc"] = "F\195\188gt einen Spieler der Blacklist hinzu, indem der Spieler anvisiert wird und /lwb blacklist in den Chat eingegeben wird, oder indem der Name in die Textbox eingetragen wird. Blockieren wird nur f\195\188r die \"Benutzen\" S\195\164tze angewendet. Um Spieler von anderen Servern hinzu zu f\195\188gen, gib ihren Namen im Format Name-Server ein. Zum Beispiel: Peter-Die silberne Hand" -- Needs review
L["Blacklist Instructions"] = "Visiere den Spieler, den du blockieren m\195\182chtest an, oder f\195\188ge ihn manuell zur Blacklist im Konfigurationsfenster hinzu" -- Needs review
L["Channel"] = "Channel" -- Needs review
L["[chargesRemaining] Charges"] = "[chargesRemaining] Aufladungen" -- Needs review
L["Charges Used:"] = "Aufladungen benutzt" -- Needs review
L["Config"] = "Config" -- Needs review
L["Counter Bar Color"] = "Z\195\164hlerbalken Farbe" -- Needs review
L["Counter Bar Texture"] = "Z\195\164hlerbalken Textur" -- Needs review
L["Counter Border"] = "Counter Border" -- Requires localization
L["Counter Border Size"] = "Counter Border Size" -- Requires localization
L["Counter Font"] = "Counter Font" -- Requires localization
L["Counter Options"] = "Z\195\164hler Optionen" -- Needs review
L["Counter Skin"] = "Counter Skin" -- Requires localization
L["Counter Skin Inset"] = "Counter Skin Inset" -- Requires localization
L["Crits:"] = "Crits" -- Needs review
L["Default"] = "Standard" -- Needs review
L["Delete List"] = "Liste l\195\182schen" -- Needs review
L["Delete List Desc"] = "Die ausgew\195\164hlte Liste mit den pers\195\182nlichen Nachrichten l\195\182schen?" -- Needs review
L["Disappear"] = "Verschwinden" -- Needs review
L["Disappear Channel Desc"] = "Channel in dem andere Spieler benachrichtigt werden, wenn dein Lichtbrunnen aus einem anderen Grunde verschwindet, als abzulaufen oder keine Aufladungen mehr zu haben." -- Needs review
L["disappearPhrases"] = "Der Lichtbrunnen ist zu fr\195\188h verschwunden. Wahrscheinlich, weil ich aus der Reichweite gerannt bin, oder getroffen wurde!" -- Needs review
L["Disappear Phrases Desc"] = "S\195\164tze die benutzt werden um andere Spieler zu benachrichtigen, wenn dein Lichtbrunnen aus einem anderen Grunde verschwindet, als abzulaufen oder keine Aufladungen mehr zu haben.\
Trenne jeden Satz mit \"Return/Enter\"." -- Needs review
L["Disappear Rate Desc"] = "H\195\164ufigkeit in welcher andere Spieler benachrichtigt werden, wenn dein Lichtbrunnen aus einem anderen Grunde verschwindet, als abzulaufen oder keine Aufladungen mehr zu haben." -- Needs review
L["Effective Healing:"] = "Effektive Heilung" -- Needs review
L["Emote"] = "Emote" -- Needs review
L["Emote As Lightwell"] = "Emote als: Lichtbrunnen" -- Needs review
L["Empty"] = "Leer" -- Needs review
L["Empty Channel Desc"] = "Channel in dem eine Nachricht ausgegeben wird, wenn jemand die letzte Aufladung deines Lichtbrunnens nutzt" -- Needs review
L["emptyPhrases"] = "Lichtbrunnen geleert, vielen Dank!" -- Needs review
L["Empty Phrases Desc"] = "S\195\164tze die benutzt werden um andere Spieler zu benachrichtigen, wenn jeman die letzte Aufladung deines Lichtbrunnens nutzt. Trenne jeden Satz mit \"Return/Enter\"." -- Needs review
L["Empty Rate Desc"] = "H\195\164ufigkeit in welcher Nachrichten an andere Spieler ausgegeben werden, wenn jemand die letzte Aufladung deines Lichtbrunnens nutzt" -- Needs review
L["Enable Counter"] = "Z\195\164hler aktivieren" -- Needs review
L["Enabled"] = "Aktiviert" -- Needs review
L["Enabled Desc"] = "Dieses Addon aktivieren oder deaktivieren" -- Needs review
L["Expire"] = "Auslaufen" -- Needs review
L["Expire Channel Desc"] = "Channel in dem andere Spieler benachrichtigt werden, wenn jemand die letzte Aufladung deines Lichtbrunnens nutzt" -- Needs review
L["expirePhrases"] = "Lichtbrunnen abgelaufen (%c Aufladungen verschwendet)" -- Needs review
L["Expire Phrases Desc"] = "S\195\164tze die benutzt werden um andere Spieler zu benachrichtigen, wenn jemand die letzte Aufladung deines Lichtbrunnens nutzt. Trenne jeden Satz mit \"Return/Enter\"." -- Needs review
L["Expire Rate Desc"] = "H\195\164ufigkeit in der andere Spieler benachrichtigt werden, wenn jemand die letzte Aufladung deines Lichtbrunnens nutzt" -- Needs review
L["General Use"] = "Benutzen allgemein" -- Needs review
L["General Use CD Desc"] = "Nachdem eine Nachricht gesendet wurde, wird keine weitere Nachricht verschickt, bis die definierte Zeit in Sekunden abgelaufen ist." -- Needs review
L["General Use Channel Desc"] = "Channel in dem andere Spieler benachrichtigt werden, wenn jemand deinen Lichtbrunnen benutzt" -- Needs review
L["General Use Desc"] = "Kontrollnachrichten, die an andere Spieler geschickt werden, die den Lichtbrunnen benutzen und kein Mitglied einer personalisierten Liste sind" -- Needs review
L["General Use Phrases Desc"] = "S\195\164tze die benutzt werden um andere Spieler zu benachrichtigen, wenn jemand deinen Lichtbrunnen nutzt. Trenne jeden Satz mit \"Return/Enter\"." -- Needs review
L["General Use Rate Desc"] = "H\195\164ufigkeit in der Spieler benachrichtigt werden, wenn jemand deinen Lichtbrunnen nutzt" -- Needs review
L["Guild"] = "Gilde" -- Needs review
L["Healing Done:"] = "Heilung gesamt" -- Needs review
L["Hide Counter When:"] = "\
\
Z\195\164hler ausblenden wenn:" -- Needs review
L["Hide Counter When Not Summoned"] = "Z\195\164hler ausblenden, wenn der Lichtbrunnen nicht aufgestellt ist" -- Needs review
L["Idle"] = "Unt\195\164tig" -- Needs review
L["Idle Channel Desc"] = "Channel in dem Nachrichten ausgegeben werden, wenn dein Lichtbrunnen nicht benutzt wird" -- Needs review
L["Idle Desc"] = "Nachricht wird gesendet, nachdem der Lichtbrunnen f\195\188r eine gewisse Zeit nicht genutzt wurde" -- Needs review
L["Idle Max Time Desc"] = "Zeit die zwischen den Meldungen gewartet wird bevor eine weitere Idle Meldung gesendet wird" -- Needs review
L["idlePhrases"] = "Lichtbrunnen:~~So lonely, oh so lonely~~ (%i Sekunden ungenutzt, %c Aufladungen \195\188brig)" -- Needs review
L["idle Phrases Desc"] = "S\195\164tze die benutzt werden um andere zu benachrichtigen, wenn der Lichtbrunnen f\195\188r eine bestimmte Zeit nicht genutzt wird. Trenne jeden Satz mit \"Return\"/\"Enter\"" -- Needs review
L["Idle Rate Desc"] = "Wahrscheinlichkeit in der andere Spieler benachrichtigt werden, wenn der Lichtbrunnen eine gewisse Zeit nicht genutzt wird" -- Needs review
L["Instance"] = "Instance" -- Requires localization
L["Lightwell Disappeared with [chargesRemaining] charges remaining!"] = "Lichtbrunnen mit [chargesRemaining] verbleibenden Aufladungen verschwunden!" -- Needs review
L["Lightwell Empty!"] = "Lichtbrunnen leer!" -- Needs review
L["Lightwell Expired with [Charges] charges remaining!"] = "Lichtbrunnen mit [Charges] verbleibenden Aufladungen abgelaufen!" -- Needs review
L["Lightwell Summoned!"] = "Lichtbrunnen aufgestellt!" -- Needs review
L["Lightwell Used by [PlayerName] ([chargesRemaining]/[chargesMax] Left)"] = "Lichtbrunnen benutzt von [PlayerName] ([chargesRemaining]/[chargesMax] \195\188brig)" -- Needs review
L["Lightwell Wasted by [PlayerName] ([chargesRemaining]/[chargesMax] Left)"] = "Lichtbrunnen verschwenderisch genutzt von [PlayerName] ([chargesRemaining]/[chargesMax] \195\188brig)" -- Needs review
L["Lock Counter Position"] = "Z\195\164hlerposition verankern" -- Needs review
L["/lwb blacklist -- blacklists your current target"] = "/lwb blacklist -- blockiert dein aktuelles Ziel" -- Needs review
L["/lwb config -- opens the configuration window"] = "/lwb config -- \195\182ffnet das Konfigurationsfenster" -- Needs review
L["Max Idle Time"] = "Maximale \"Ungenutzt\" Zeit" -- Needs review
L["Message Cooldown"] = "Nachricht Abklingzeit" -- Needs review
L["Message on Last Use"] = "Nachricht f\195\188r letzte Nutzung" -- Needs review
L["Message on Last Use Desc"] = "Sende eine Nachricht f\195\188r die letzte Nutzung des Lichtbrunnens" -- Needs review
L["Modify Profiles"] = "Profile bearbeiten" -- Needs review
L["Multiconsumption"] = "Mehrfach-Nutzung" -- Needs review
L["Multiconsumption Channel Desc"] = "Channel f\195\188r die Benachrichtigungen, wenn ein Spieler den Lichtbrunnen doppelt anklickt und dadurch mehrere Aufladungen verbraucht werden, obwohl nur eine Heilung erzeugt wird" -- Needs review
L["Multiconsumption Desc"] = "Dieses Ereignis erkennt, wenn ein Spieler den Lichtbrunnen doppelt anklickt und dadurch mehrere Aufladungen f\195\188r eine einzige Anwendung des Lichtbrunnen Buffs verbraucht. Normalerweise wird keine weitere Aufladung des Lichtbrunnen von einem Spieler aufgebraucht, der den Buff schon hat, aber es gibt eine geringe Wahrscheinlichkeit, dass trotzdem eine weitere Aufladung verbraucht wird, bevor der Lichtbrunnen Buff angewendet wird - das f\195\188hrt dazu, dass mehrere Aufladungen verbaucht werden" -- Needs review
L["multiconsumptionPhrases"] = "%u, ein Lag hat dazu gef\195\188hrt, dass eine Lichtbrunnen Aufladung verschwendet wurde. Um das zu verhindern, klicke bitte nicht doppelt auf den Lichtbrunnen." -- Needs review
L["Multiconsumption Phrases Desc"] = "S\195\164tze die ausgegeben werden, wenn ein Spieler den Lichtbrunnen doppelt anklickt und dadurch mehrere Aufladungen verbraucht werden, obwohl nur eine Heilung erzeugt wird. Trenne jeden Satz mit \"Return/Enter\"." -- Needs review
L["Multiconsumption Rate Desc"] = "H\195\164ufigkeit in der Nachrichten ausgegeben werden, wenn andere Spieler den Lichtbrunnen doppelt anklicken und dadurch mehrere Aufladungen verbraucht werden, obwohl nur eine Heilung erzeugt wird." -- Needs review
L["Multiple Lightwell Charges Used by [PlayerName] ([chargesRemaining]/[chargesMax] Left)"] = "Mehrfache Lichtbrunnennutzung von [PlayerName] ([chargesRemaining]/[chargesMax] \195\188brig)" -- Needs review
L["New List"] = "Neue Liste" -- Needs review
L["New List Desc"] = "Gib einen Namen f\195\188r deine neue Liste f\195\188r personalisierte Nachrichten an" -- Needs review
L["No lightwell up"] = "Kein Lichtbrunnen aufgestellt" -- Needs review
L["None"] = "-Keine-" -- Needs review
L["Officer"] = "Offizier" -- Needs review
L["Out of Combat"] = "Au\195\159erhalb des Kampfes" -- Needs review
L["Out of Combat Desc"] = "Sende \"Abgelaufen\", \"Verschwunden\" und \"Unt\195\164tig\" Nachrichten nach dem Kampf" -- Needs review
L["Over Healing:"] = "\195\156berheilung" -- Needs review
L["Party"] = "Gruppe" -- Needs review
L["Personalized Use"] = "Personalisierte Nutzung" -- Needs review
L["Personalized Use Desc"] = "Personalisierte Nachrichten, die an spezielle Spieler geschickt werden, wenn sie den Lichtbrunnen anklicken. Ersetzt die \"Benutzung allgemein\" Nachrichten." -- Needs review
L["Personal List CD Desc"] = "Nachdem eine Nachricht geschickt wurde, wird keine weitere Nachricht an Spieler gesendet, bis die definierte Zeit abgelaufen ist." -- Needs review
L["Personal List Channel Desc"] = "Channel in dem die Nachrichten an die Spieler, die in dieser Liste sind, ausgegeben werden, wenn sie den Lichtbrunnen anklicken" -- Needs review
L["Personal List Phrases Desc"] = "S\195\164tze die benutzt werden um die Spieler, die in dieser Liste sind, zu benachrichtigen, wenn sie den Lichtbrunnen anklicken. Trenne jeden Satz mit \"Return\"/\"Enter\"." -- Needs review
L["Personal List Rate Desc"] = "H\195\164ufigkeit mit der die Spieler in dieser Liste benachrichtigt werden, wenn sie den Lichtbrunnen anklicken" -- Needs review
L["Phrases"] = "S\195\164tze" -- Needs review
L["Placeholder Desc"] = "Folgende Platzhalter werden wie folgt ersetzt: %u = Spielername des Lichtbrunnen Benutzers bei \"Benutzen\" Ereignissen. %p = dein Name. %c = Verbleibende Lichtbrunnen Aufladungen. %x = Benutzte Lichtbrunnen Ausladungen. %m = Maximale Lichtbrunnen Aufladungen. %t = Sekunden, die der Lichtbrunnen schon steht. %l =Sekunden, die verbleiben bevor der Lichtbrunnen verschwindet. %i = Sekunden die der Lichtbrunnen nicht genutzt wurde." -- Needs review
L["Player Unblacklisted"] = "[PlayerName] wurde von der Blackliste entfernt" -- Needs review
L["Profile changed to: [profileName]"] = "Profil ge\195\164ndert zu [profileName]" -- Needs review
L["Raid"] = "Schlachtzug" -- Needs review
L["Raid Warning"] = "Schlachtzugswarnung" -- Needs review
L["Rate"] = "Rate" -- Needs review
L["Remove Player"] = "Spieler entfernen" -- Needs review
L["Remove Player Desc"] = "Spieler aus dieser Nachrichtenliste entfernen" -- Needs review
L["Results of Lightwell:"] = "Ergebnisse des Lichtbrunnens" -- Needs review
L["Say"] = "Sagen" -- Needs review
L["Say As Lightwell"] = "Sagen als: Lichtbrunnen" -- Needs review
L["Select A List"] = "W\195\164hle eine Liste" -- Needs review
L["Select A List Desc"] = "W\195\164hle eine existierende Liste um Spieler oder S\195\164tze hinzu zu f\195\188gen oder andere Optionen zu \195\164ndern " -- Needs review
L["Smart"] = "Smart" -- Needs review
L["Summon"] = "Aufstellen" -- Needs review
L["Summon Channel Desc"] = "Channel in dem Nachrichten ausgegeben werden, wenn du einen Lichtbrunnen aufstellst" -- Needs review
L["summonPhrases"] = "Bitte nutzt meinen Lichtbrunnen! (%m Aufladungen)\
Lichtbrunnen aufgestellt! (%m Aufladungen)" -- Needs review
L["Summon Phrases Desc"] = "S\195\164tze die ausgegeben werden, wenn du einen Lichtbrunnen aufstellst. Trenne jeden Satz mit \"Return\"/\"Enter\"." -- Needs review
L["Summon Rate Desc"] = "H\195\164ufigkeit in der andere benachrichtigt werden, wenn du einen Lichtbrunnen aufstellst" -- Needs review
L["Support Lightspring"] = "Unterst\195\188tzen Lichtquell" -- Needs review
L["Support Lightspring Desc"] = "Tivieren ank\195\188ndigungen f\195\188r Lichtquell" -- Needs review
L["Talk to Strangers"] = "Benachrichtigung an Fremde" -- Needs review
L["Talk to Strangers Desc"] = "Sende Benachrichtigungen an Leute, die nicht in deiner Gruppe oder deinem Schlachtzug sind" -- Needs review
L["Unblacklist"] = "Un-blacklist" -- Needs review
L["Unblacklist Desc"] = "Um einen Spieler von der Blacklist zu entfernen, benutze das Dropdown Men\195\188 um den Spielernamen auszuw\195\164hlen" -- Needs review
L["Un-blacklist player"] = "Un-blacklist Spieler" -- Needs review
L["usePhrases"] = "Danke dass du meinen Lichtbrunnen benutzt, %u. (%c von %m Aufladungen \195\188brig)\
%u hat den Lichtbrunnen benutzt! (%c von %m Aufladungen \195\188brig)" -- Needs review
L["Waste"] = "Verschwendung" -- Needs review
L["Waste Channel Desc"] = "Channel in dem Benachrichtigungen ausgegeben werden, wenn jemand deinen Lichtbrunnen verschwenderisch nutzt" -- Needs review
L["Waste Cut Off"] = "Verschwendungsbereich" -- Needs review
L["Waste Cut Off Desc"] = "Wenn jemand mehr HP als angegeben hat, w\195\164hrend er den Lichtbrunnen nutzt, wird er ein Verschwender sein. Es gibt keine M\195\182glichkeit die HP von jemanden zu bestimmen, der nicht in deiner Gruppe oder deinem Schlachtzug ist und deswegen werden jene nicht als Verschwender erkannt." -- Needs review
L["wastePhrases"] = "Danke dass du meinen Lichbrunnen benutzt, %u, aber bitte sei dir sicher, dass du Heilung ben\195\182tigst. (%c von %m Aufladungen \195\188brig)" -- Needs review
L["Waste Phrases Desc"] = "S\195\164tze die benutzt werden, wenn jemand eine Aufladung deines Lichtbrunnens verschwendet. Trenne jeden Satz mit \"Return\"/\"Enter\"" -- Needs review
L["Waste Rate Desc"] = "H\195\164ufigkeit in welcher andere benachrichtigt werden, wenn jemand deinen Lichbrunnen verschwenderisch nutzt" -- Needs review
L["Whisper"] = "Fl\195\188stern" -- Needs review
L["Yell"] = "Schreien" -- Needs review
