_G["LWB"] = _G["LWB"] or {}
local LWB = _G["LWB"]
local L = LibStub("AceLocale-3.0"):NewLocale("LWB","ptBR")
if not L then return end


L["1 Charge"] = "1 Charge" -- Requires localization
L["Absorbed:"] = "Absorbed:" -- Requires localization
L["Added to Blacklist"] = "[PlayerName] agora est\195\161 no ignore" -- Needs review
L["Add Player"] = "Adicionar jogador" -- Needs review
L["Add Player Desc"] = "Adicionar um jogador a receber mensagens desta lista" -- Needs review
L["Alert to Self"] = "Alerta para Auto" -- Needs review
L["Alert to Self Desc"] = "Alert to you when something happens with your Lightwell" -- Requires localization
L["Already Blacklisted"] = "[PlayerName] j\195\161 est\195\161 no ignore" -- Needs review
L["Already in List"] = "Player is already in list [currentList]" -- Requires localization
L["Battleground"] = "Campo de batalha" -- Needs review
L["Begin Pulsing"] = "Begin Pulsing" -- Requires localization
L["Blacklist"] = "Ignore" -- Needs review
L["Blacklist Desc"] = "Add a player by targeting the player and typing /lwb blacklist or by typing their name the text box. Blacklisting only applies to the Use phrases. To add players from other servers, enter their name in the form Name-Server. For example Peter-Silver Hand" -- Requires localization
L["Blacklist Instructions"] = "Target the player you want to blacklist or add them manually in the configuration window" -- Requires localization
L["Channel"] = "Canal" -- Needs review
L["[chargesRemaining] Charges"] = "[chargesRemaining] Charges" -- Requires localization
L["Charges Used:"] = "Charges Used:" -- Requires localization
L["Config"] = "Config" -- Requires localization
L["Counter Bar Color"] = "Counter Bar Color" -- Requires localization
L["Counter Bar Texture"] = "Counter Bar Texture" -- Requires localization
L["Counter Border"] = "Counter Border" -- Requires localization
L["Counter Border Size"] = "Counter Border Size" -- Requires localization
L["Counter Font"] = "Counter Font" -- Requires localization
L["Counter Options"] = "Counter Options" -- Requires localization
L["Counter Skin"] = "Counter Skin" -- Requires localization
L["Counter Skin Inset"] = "Counter Skin Inset" -- Requires localization
L["Crits:"] = "Crits:" -- Requires localization
L["Default"] = "Padr\195\163o" -- Needs review
L["Delete List"] = "Deleta da lista" -- Needs review
L["Delete List Desc"] = "Excluir lista Desc." -- Needs review
L["Disappear"] = "Desaparecer" -- Needs review
L["Disappear Channel Desc"] = "Channel in which to message others when your Lightwell disappears for a reason other than expiring or running out of charges." -- Requires localization
L["disappearPhrases"] = "Lightwell has disappeared early! Most likely due to me running out of range or getting hit for more than 30%!" -- Requires localization
L["Disappear Phrases Desc"] = "Phrases to use when messaging others when your Lightwell disappears for a reason other than expiring or running out of charges. Separate each phrase with a return/enter." -- Requires localization
L["Disappear Rate Desc"] = "Rate at which to message others when your Lightwell disappears for a reason other than expiring or running out of charges." -- Requires localization
L["Effective Healing:"] = "Effective Healing:" -- Requires localization
L["Emote"] = "Emote" -- Needs review
L["Emote As Lightwell"] = "Emote As Lightwell" -- Requires localization
L["Empty"] = "Vazio" -- Needs review
L["Empty Channel Desc"] = "Channel in which to message others when someone empties your Lightwell" -- Requires localization
L["emptyPhrases"] = "Lightwell empty, thank you!" -- Requires localization
L["Empty Phrases Desc"] = "Phrases to use when messaging others when someone empties your Lightwell. Separate each phrase with a return/enter." -- Requires localization
L["Empty Rate Desc"] = "Rate at which to message others when someone empties your Lightwell" -- Requires localization
L["Enable Counter"] = "Enable Counter" -- Requires localization
L["Enabled"] = "Habilidado" -- Needs review
L["Enabled Desc"] = "Enable or disable this addon." -- Requires localization
L["Expire"] = "Acabou" -- Needs review
L["Expire Channel Desc"] = "Channel in which to message others when someone empties your Lightwell" -- Requires localization
L["expirePhrases"] = "Lightwell expired! (%c Charges Wasted)" -- Requires localization
L["Expire Phrases Desc"] = "Phrases to use when messaging others when someone empties your Lightwell. Separate each phrase with a return/enter." -- Requires localization
L["Expire Rate Desc"] = "Rate at which to message others when someone empties your Lightwell" -- Requires localization
L["General Use"] = "General Use" -- Requires localization
L["General Use CD Desc"] = "After a message is sent, another message will not be sent until the specified number of seconds has passed." -- Requires localization
L["General Use Channel Desc"] = "Channel in which to message others when someone uses your Lightwell" -- Requires localization
L["General Use Desc"] = "Controls messages sent to players who use the lightwell and are not a member of a personalized list" -- Requires localization
L["General Use Phrases Desc"] = "Phrases to use when messaging others when someone uses your Lightwell. Separate each phrase with a return/enter" -- Requires localization
L["General Use Rate Desc"] = "Rate at which to message others when someone uses your Lightwell" -- Requires localization
L["Guild"] = "Guilda" -- Needs review
L["Healing Done:"] = "Healing Done:" -- Requires localization
L["Hide Counter When:"] = "\
\
 Hide Counter When:" -- Requires localization
L["Hide Counter When Not Summoned"] = "Not Summoned" -- Requires localization
L["Idle"] = "Idle" -- Requires localization
L["Idle Channel Desc"] = "Channel with which to message others when the lightwell is idle" -- Requires localization
L["Idle Desc"] = "Message is sent after the lightwell has been unused for a given period of time" -- Requires localization
L["Idle Max Time Desc"] = "Time to wait before sending an idle message and between sending each subsequent message" -- Requires localization
L["idlePhrases"] = "Lightwell:~~So lonely, oh so lonely~~ (%i seconds idle, %c charges remaining)" -- Requires localization
L["idle Phrases Desc"] = "Phrases to use when messaging others when the lightwell has been idle for the specified amount of time. Separate each phrase with a return/enter" -- Requires localization
L["Idle Rate Desc"] = "Rate at which to message others when the lightwell has been idle for the specified amount of time" -- Requires localization
L["Instance"] = "Instance" -- Requires localization
L["Lightwell Disappeared with [chargesRemaining] charges remaining!"] = "Lightwell Disappeared with [chargesRemaining] charges remaining!" -- Requires localization
L["Lightwell Empty!"] = "Lightwell Empty!" -- Requires localization
L["Lightwell Expired with [Charges] charges remaining!"] = "Lightwell Expired with [Charges] charges remaining!" -- Requires localization
L["Lightwell Summoned!"] = "Lightwell Summoned!" -- Requires localization
L["Lightwell Used by [PlayerName] ([chargesRemaining]/[chargesMax] Left)"] = "Lightwell Used by [PlayerName] ([chargesRemaining]/[chargesMax] Left)" -- Requires localization
L["Lightwell Wasted by [PlayerName] ([chargesRemaining]/[chargesMax] Left)"] = "Lightwell Wasted by [PlayerName] ([chargesRemaining]/[chargesMax] Left)" -- Requires localization
L["Lock Counter Position"] = "Lock Counter Position" -- Requires localization
L["/lwb blacklist -- blacklists your current target"] = "/lwb blacklist -- blacklists your current target" -- Requires localization
L["/lwb config -- opens the configuration window"] = "/lwb config -- opens the configuration window" -- Requires localization
L["Max Idle Time"] = "Max Idle Time" -- Requires localization
L["Message Cooldown"] = "Message Cooldown" -- Requires localization
L["Message on Last Use"] = "Message on Last Use" -- Requires localization
L["Message on Last Use Desc"] = "Send a Message for the last use of the lightwell" -- Requires localization
L["Modify Profiles"] = "Modify Profiles" -- Requires localization
L["Multiconsumption"] = "Multi-consumption" -- Requires localization
L["Multiconsumption Channel Desc"] = "Channel with which to message others when players quickly double-click the lightwell, causing multiple charges to be consumed with only one heal generated" -- Requires localization
L["Multiconsumption Desc"] = "This event recognizes when a player has double-clicked the ligthtwell, causing multiple charges to be consumed for a single application of the Lightwell Buff. Usually the lightwell will not allow another charge to be consumed by a player that already has the buff, but there is a brief moment where multiple commands to consume a charge can be sent before the lightwell renew buff has been applied - causing multiple charges to be consumed." -- Requires localization
L["multiconsumptionPhrases"] = "%u, server lag has caused an extra lightwell charge to be wasted. To prevent this from happening, please do not double-click the lightwell." -- Requires localization
L["Multiconsumption Phrases Desc"] = "Phrases to use when messaging others when players quickly double-click the lightwell, causing multiple charges to be consumed with only one heal generated. Separate each phrase with a return/enter." -- Requires localization
L["Multiconsumption Rate Desc"] = "Rate at which to message others when players quickly double-click the lightwell, causing multiple charges to be consumed with only one heal generated." -- Requires localization
L["Multiple Lightwell Charges Used by [PlayerName] ([chargesRemaining]/[chargesMax] Left)"] = "Multiple Lightwell Charges Used by [PlayerName] ([chargesRemaining]/[chargesMax] Left)" -- Requires localization
L["New List"] = "New List" -- Requires localization
L["New List Desc"] = "Give a name to your new list of personalized messages" -- Requires localization
L["No lightwell up"] = "No lightwell up" -- Requires localization
L["None"] = "Nenhum" -- Needs review
L["Officer"] = "Officer" -- Needs review
L["Out of Combat"] = "Out of Combat" -- Requires localization
L["Out of Combat Desc"] = "Send Expire, Disappear and Idle messages after leaving combat" -- Requires localization
L["Over Healing:"] = "Over Healing:" -- Requires localization
L["Party"] = "Grupo" -- Needs review
L["Personalized Use"] = "Personalized Use" -- Requires localization
L["Personalized Use Desc"] = "Personalize messages to be sent to specific players when they click the lightwell. Replaces the General Use messages." -- Requires localization
L["Personal List CD Desc"] = "After a message is sent, another message will not be sent to the players on this list until the specified amount of time has passed." -- Requires localization
L["Personal List Channel Desc"] = "Channel with which to message players on this list when they click the lightwell" -- Requires localization
L["Personal List Phrases Desc"] = "Phrases to use when messaging players on this list when they click the lightwell. Separate each phrase with a return/enter." -- Requires localization
L["Personal List Rate Desc"] = "Rate at which to message players on this list when they click the lightwell." -- Requires localization
L["Phrases"] = "Phrases" -- Requires localization
L["Placeholder Desc"] = "Any occurrence of the following placeholders will be replaced as follows: %u = Lightwell User's name in Use events. %p = your name. %c = lightwell charges remaining. %x = lightwell charges used. %m = maximum lightwell charges. %t = seconds the lightwell has been out. %l = seconds remaining before lightwell expires. %i = seconds the lightwell has been idle." -- Requires localization
L["Player Unblacklisted"] = "[PlayerName] has been removed from the blacklist." -- Requires localization
L["Profile changed to: [profileName]"] = "Profile changed to: [profileName]" -- Requires localization
L["Raid"] = "Raide" -- Needs review
L["Raid Warning"] = "Raide aviso" -- Needs review
L["Rate"] = "Rate" -- Requires localization
L["Remove Player"] = "Remove Player" -- Requires localization
L["Remove Player Desc"] = "Remove player from receiving messages from this list." -- Requires localization
L["Results of Lightwell:"] = "Results of Lightwell:" -- Requires localization
L["Say"] = "Falar" -- Needs review
L["Say As Lightwell"] = "Say As Lightwell" -- Requires localization
L["Select A List"] = "Select A List" -- Requires localization
L["Select A List Desc"] = "Select an existing list to add players, phrases, and modify other options" -- Requires localization
L["Smart"] = "Smart" -- Requires localization
L["Summon"] = "Summon" -- Requires localization
L["Summon Channel Desc"] = "Channel in which to message others when you Summon a Lightwell" -- Requires localization
L["summonPhrases"] = "Please use my Lightwell! (%m Charges)\
Lightwell Summoned! (%m Charges)" -- Requires localization
L["Summon Phrases Desc"] = "Phrases to use when messaging others when you Summon a Lightwell. Separate each phrase with a return/enter." -- Requires localization
L["Summon Rate Desc"] = "Rate at which to message others when you Summon a Lightwell" -- Requires localization
L["Support Lightspring"] = "Support Lightspring" -- Requires localization
L["Support Lightspring Desc"] = "Enable announcements for lightspring" -- Requires localization
L["Talk to Strangers"] = "Talk to Strangers" -- Requires localization
L["Talk to Strangers Desc"] = "Send messages for people not in your party or raid" -- Requires localization
L["Unblacklist"] = "Unblacklist" -- Requires localization
L["Unblacklist Desc"] = "To remove a player from the blacklist, use the dropdown menu to select the player's name." -- Requires localization
L["Un-blacklist player"] = "Un-blacklist player" -- Requires localization
L["usePhrases"] = "Thank you for using my Lightwell, %u. (%c of %m Charges Left)\
%u has used the lightwell! (%c of %m Charges Left)" -- Requires localization
L["Waste"] = "Waste" -- Requires localization
L["Waste Channel Desc"] = "Channel in which to message others when someone wastes your Lightwell" -- Requires localization
L["Waste Cut Off"] = "Waste Cut Off" -- Requires localization
L["Waste Cut Off Desc"] = "If some one has more health than this when they use the Lightwell they will be a waster. There is no way to get the health of someone not in your party or raid so they are unable to be detected as a waster." -- Requires localization
L["wastePhrases"] = "Thank you for using my Lightwell, %u, but please try to make sure you need it. (%c of %m Charges Left)" -- Requires localization
L["Waste Phrases Desc"] = "Phrases to use when messaging others when someone wastes a charge on your Lightwell. Separate each phrase with a return/enter" -- Requires localization
L["Waste Rate Desc"] = "Rate at which to message others when someone wastes your Lightwell" -- Requires localization
L["Whisper"] = "Sussurra" -- Needs review
L["Yell"] = "Yell" -- Requires localization
